(define (problem exploration-generated)
    (:domain exploration)
    
    (:objects
        vehB vehG - robot
        l11 l12 l13 l21 l22 l23 l31 l32 l33 - location
    )
    
    (:init
        ;; Robot starting positions
        (at vehB l11)
        (at vehG l11)

        ;; Traversability and costs (based on terrain types)
        (can-traverse vehB l11)
        (= (traverse-cost vehB l11) 1)
        (can-traverse vehG l11)
        (= (traverse-cost vehG l11) 1)
        (can-traverse vehB l12)
        (= (traverse-cost vehB l12) 1)
        (can-traverse vehB l13)
        (= (traverse-cost vehB l13) 1)
        (can-traverse vehG l13)
        (= (traverse-cost vehG l13) 1)
        (can-traverse vehB l21)
        (= (traverse-cost vehB l21) 1)
        (can-traverse vehG l21)
        (= (traverse-cost vehG l21) 1)
        (can-traverse vehB l22)
        (= (traverse-cost vehB l22) 5)
        (can-traverse vehG l22)
        (= (traverse-cost vehG l22) 5)
        (can-traverse vehB l23)
        (= (traverse-cost vehB l23) 1)
        (can-traverse vehG l23)
        (= (traverse-cost vehG l23) 1)
        (can-traverse vehB l31)
        (= (traverse-cost vehB l31) 1)
        (can-traverse vehG l31)
        (= (traverse-cost vehG l31) 1)
        (can-traverse vehB l32)
        (= (traverse-cost vehB l32) 1)
        (can-traverse vehG l32)
        (= (traverse-cost vehG l32) 1)
        (can-traverse vehB l33)
        (= (traverse-cost vehB l33) 1)
        (can-traverse vehG l33)
        (= (traverse-cost vehG l33) 1)

        ;; Observation capabilities (based on observation types)
        (can-observe vehB l11)
        (can-observe vehG l11)
        (can-observe vehB l12)
        (can-observe vehG l12)
        (can-observe vehB l13)
        (can-observe vehB l21)
        (can-observe vehG l21)
        (can-observe vehB l22)
        (can-observe vehG l22)
        (can-observe vehB l23)
        (can-observe vehG l23)
        (can-observe vehB l31)
        (can-observe vehG l31)
        (can-observe vehG l32)
        (can-observe vehB l33)
        (can-observe vehG l33)

        ;; Grid adjacency
        (adjacent l11 l12) (adjacent l12 l11)
        (adjacent l11 l21) (adjacent l21 l11)
        (adjacent l12 l13) (adjacent l13 l12)
        (adjacent l12 l22) (adjacent l22 l12)
        (adjacent l13 l23) (adjacent l23 l13)
        (adjacent l21 l22) (adjacent l22 l21)
        (adjacent l21 l31) (adjacent l31 l21)
        (adjacent l22 l23) (adjacent l23 l22)
        (adjacent l22 l32) (adjacent l32 l22)
        (adjacent l23 l33) (adjacent l33 l23)
        (adjacent l31 l32) (adjacent l32 l31)
        (adjacent l32 l33) (adjacent l33 l32)

        (= (total-cost) 0)
    )
    
    (:goal (and
        ;; All locations explored
        (explored l11) (explored l12) (explored l13)
        (explored l21) (explored l22) (explored l23)
        (explored l31) (explored l32) (explored l33)
        ;; Robot goal positions
        (at vehB l33)
        (at vehG l33)
    ))
    
    (:metric minimize (total-cost))
)