(define (problem road-8)
    (:domain road)
    (:objects
        v1 - vehicle
        v2 - bulldozer
        l1 l2 l3 l4 l5 l6 l7 l8 l9 - location
    )
    (:init
        (at v1 l1)
        (at v2 l1)
        (rubble l2)
        (adjacent l1 l2)
        (adjacent l2 l1)
        (adjacent l2 l3)
        (adjacent l3 l2)
        (adjacent l3 l4)
        (adjacent l4 l3)
        (adjacent l4 l5)
        (adjacent l5 l4)
        (adjacent l5 l6)
        (adjacent l6 l5)
        (adjacent l6 l7)
        (adjacent l7 l6)
        (adjacent l7 l8)
        (adjacent l8 l7)
        (adjacent l8 l9)
        (adjacent l9 l8)
    )
    (:goal (at v1 l9))
)